# Generated by Django 5.0 on 2023-12-18 14:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('23675fd4-9829-496e-803a-75f54fa5771f'), editable=False, primary_key=True, serialize=False),
        ),
    ]
