# Generated by Django 5.0.2 on 2024-02-13 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back_end', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='code',
            new_name='Code',
        ),
    ]
