# Generated by Django 5.0.2 on 2024-02-13 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back_end', '0002_rename_code_room_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='Code',
            new_name='code',
        ),
    ]
