# Generated by Django 5.0.3 on 2024-03-17 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Himachal Pradesh', 'Himachal Pradesh'), ('Greater Noida', 'Greater Noida'), ('Udham Singh nagar', 'Udham Singh nagar'), ('Udisa', 'Udisa'), ('Karnatak', 'Karnatak'), ('Goa', 'Goa'), ('Uttar Pradesh', 'Uttar Pradesh'), ('jaspur Udham Singh nagar', 'jaspur Udham Singh nagar'), ('Punjab', 'Punjab'), ('Bihar', 'Bihar'), ('Sikkim', 'Sikkim'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Gujrat', 'Gujrat'), ('Rajisthan', 'Rajisthan'), ('Noida', 'Noida'), ('Tamil Nadu', 'Tamil Nadu'), ('Delhi', 'Delhi'), ('Telangana', 'Telangana'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Tripura', 'Tripura'), ('Hariyana', 'Hariyana'), ('West Bengal', 'West Bengal'), ('Assam', 'Assam'), ('Mumbai', 'Mumbai'), ('Uttarakhan', 'Uttarakhan')], max_length=100),
        ),
    ]
